name: Allure Docker Service UI Workflow

on:
  push:
    branches:
      - "*"

    tags:
      - v*

  pull_request:

env:
  DOCKER_IMAGE: frankescobar/allure-docker-service-ui

permissions:
  id-token: write
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Pulling code
        uses: actions/checkout@v2

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.IAM_ROLE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Preparing
        id: prepare
        run: |
          DOCKER_PLATFORMS=linux/amd64
          VERSION=na
          TAGS="--tag ${DOCKER_IMAGE}:na"

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            if [[ $GITHUB_REF == *"beta"* ]]; then
                TAGS="--tag ${DOCKER_IMAGE}:${VERSION} --tag ${DOCKER_IMAGE}:beta"
            else
                TAGS="--tag ${DOCKER_IMAGE}:${VERSION} --tag ${DOCKER_IMAGE}:latest"
            fi
          fi

          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=buildx_args::--platform ${DOCKER_PLATFORMS} \
            --build-arg VERSION=${VERSION} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VCS_REF=${GITHUB_SHA::8} \
            ${TAGS} --file docker/Dockerfile .

      - name: Setting up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setting up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Docker Building
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          REPO_PATH: allure-docker-service-ui
        run: |
          docker build --no-cache \
          -t $ECR_REGISTRY/$REPO_PATH:$IMAGE_TAG \
          -t $ECR_REGISTRY/$REPO_PATH:latest \
          ${{ steps.prepare.outputs.buildx_args }}

      - name: Docker Publishing
        if: success()
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO_PATH: allure-docker-service-ui
        run: |
          echo "DOCKER PUSH: pushing - $ECR_REGISTRY/$REPO_PATH:latest"
          docker push $ECR_REGISTRY/$REPO_PATH:latest
